# build with dockerfile first then run everything here with the following
# build with docker compose up --build
# Windows issue with port 3000 authorization issue
# open cmd as admin and run the following
# net stop winnat
# run `docker compose up --build` in wsl terminal
# net start winnat

version: "3.9"

services:
  api:
    image: authentication-wo-devise-rails-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
